-- 스케치북 관련 쿼리
CREATE TABLE "HAPPY"."LPSKETCHBOOK" 
   ( "SKETCH_ID" VARCHAR2(20), 
 "USER_EMAIL" VARCHAR2(50), 
 "SKETCH_TITLE" VARCHAR2(50), 
 "SKETCH_THEME" VARCHAR2(20), 
 "SKETCH_SHARE" CHAR(1), 
 "SKETCH_DELFLAG" CHAR(1), 
 "SKETCH_SPATH" VARCHAR2(100), 
 "SKETCH_BLOCK" CHAR(1)
   );


CREATE TABLE "HAPPY"."LPCOLLECT" 
   ( "COL_ID" VARCHAR2(20), 
 "USER_EMAIL" VARCHAR2(50), 
 "SKETCH_ID" VARCHAR2(20), 
 "COL_SCRAPE" CHAR(1), 
 "COL_LIKE" CHAR(1)
   );